title: Guilherme Santos
description: Engenharia de Software Embarcado & Hardware
theme: minima
header_image: /assets/imagens/logo_gs_grande.png

# Isso criará os links automaticamente no menu do topo
header_pages:
  - index.md
  - projetos.md
  - aprendizados.md
  - entretenimento.md
  - filosofias.md
