#title: Guilherme Santos
#logo: /assets/imagens/logo_gs_grande.png
description: Engenharia de Software Embarcado & Hardware
theme: minima

# Isso criará os links automaticamente no menu do topo
header_pages:
  - index.md
  - profissional.md
  - posts.md
