title: Guilherme Santos
email: guistech@gmail.com
description: >- # descrição do seu perfil
  Minhas anotações aleatórias e perfil pessoal.
baseurl: "" 
url: "https://guilhermesantos.dev.br"
theme: minima
